// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoteRonaldoVsMessi.Infrastructure;

namespace VoteRonaldoVsMessi.Infrastructure.Migrations
{
    [DbContext(typeof(VoteContextDbApp))]
    [Migration("20191013194629_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VoteRonaldoVsMessi.Infrastructure.Models.Vote", b =>
                {
                    b.Property<Guid>("VoterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("VotedFor")
                        .HasColumnName("Vote");

                    b.HasKey("VoterId");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
